This is makeindex, version 2.15 [TeX Live 2017] (kpathsea + Thai support).
Scanning style file ./principal.ist.............................done (29 attributes redefined, 0 ignored).
Scanning input file principal.acn....done (4 entries accepted, 0 rejected).
Sorting entries....done (10 comparisons).
Generating output file principal.acr....done (11 lines written, 0 warnings).
Output written in principal.acr.
Transcript written in principal.alg.
